### ISSUE TITLE
[VULN] 🔓 Shellshock

### ISSUE THREAD

**Issue by scriptingislife** [becksteadn/Bytes-Of-Swiss#2]
**Description**
Shellshock takes advantage of a vulnerability in older version of the Bash shell to execute commands remotely.

**What does the vulnerability require?**
Shellshock is most often found in `cgi-bin` capabilities of web servers but can also be used in mail servers.

**What weaknesses does this create in a machine?**
Allows remote command execution.

**Additional context**

https://blog.cloudflare.com/inside-shellshock/

https://www.surevine.com/shellshocked-a-quick-demo-of-how-easy-it-is-to-exploit/

https://code-maven.com/set-up-cgi-with-apache

**TODO**

- [x]  Create role from cookiecutter
- [x]  Modify molecule.yml
    - [x]  Forward ports
    - [x]  Change/add instances
- [x]  Add dependencies to meta/main.yml
    - [x]  Create dependency roles if they don't already exist
- [x]  Write role
- [x]  Write tests
- [x]  Update README.md
