### ISSUE TITLE
[VULN] 🔓 SQL Injection Web App

### ISSUE THREAD

**Issue by scriptingislife** [becksteadn/Bytes-Of-Swiss#21]
**Description**
A web app that has SQL injection.

**What does the vulnerability require?**
A web server, PHP, and database.

**What weaknesses does this create in a machine?**
User information can be disclosed. Plaintext passwords?

**Additional context**
https://www.w3schools.com/sql/sql_injection.asp

http://www.tizag.com/mysqlTutorial/mysql-php-sql-injection.php

**TODO**

- [x]  Create role from cookiecutter
- [x]  Modify molecule.yml
    - [x]  Forward ports
    - [x]  Change/add instances
- [x]  Add dependencies to meta/main.yml
    - [x]  Create dependency roles if they don't already exist
- [ ]  Write role
- [ ]  Write tests
- [ ]  Update README.md
