### ISSUE TITLE
[VULN] 🔓 Drupalgeddon2

### ISSUE THREAD

**Issue by scriptingislife** [becksteadn/Bytes-Of-Swiss#36]
**Description**
A vulnerable Drupal site that allows RCE.

**What does the vulnerability require?**
A specially crafted request.
Web server.
PHP.

**What weaknesses does this create in a machine?**
RCE as an anonymous visitor.

**Additional context**
https://www.rapid7.com/db/modules/exploit/unix/webapp/drupal_drupalgeddon2

**TODO**

- [ ]  Create role from cookiecutter
- [ ]  Modify molecule.yml
    - [ ]  Forward ports
    - [ ]  Change/add instances
- [ ]  Add dependencies to meta/main.yml
    - [ ]  Create dependency roles if they don't already exist
- [ ]  Write role
- [ ]  Write tests
- [ ]  Update README.md
