### ISSUE TITLE
[SERV]  🧰 SMB Server

### ISSUE THREAD

**Issue by scriptingislife** [becksteadn/Bytes-Of-Swiss#5]
**Description**
Create a Sambda server to host file shares.

**What kind of vulnerabilities can use this service?**
 Shares can be made to have anonymous or write access.

**What other services are needed?**
None.

**Additional context**
https://tutorials.ubuntu.com/tutorial/install-and-configure-samba

https://www.howtoforge.com/samba-server-installation-and-configuration-on-centos-7

**TODO**

- [x]  Create role from cookiecutter
- [x]  Modify molecule.yml
    - [ ]  Forward ports
    - [ ]  Change/add instances
- [x]  Add dependencies to meta/main.yml
    - [ ]  Create dependency roles if they don't already exist
- [x]  Write role
- [x]  Write tests
- [x]  Update README.md
